.\" $Id: dangen.6,v 1.4 2009/11/10 19:04:59 oohara Exp $
.TH DANGEN 6 "Wed, 11 Nov 2009" "Project Geeste" "dangen manual"
.SH NAME
dangen \- shoot 'em up game where accurate shooting matters
.SH SYNOPSIS
.B dangen
[
.BI "\-\-free\-select"
]
[
.BI "\-\-full\-screen"
]
[
.BI "\-\-help"
]
[
.BI "\-\-slow"
]
[
.BI "\-\-version"
]
.SH DESCRIPTION
dangen is a shoot 'em up game that attach importance to accuracy of shooting.
With the combination of the cursor key and the shot button, you can shoot
at your side or even at your back.  Get the bonus point by hitting the
enemy without a miss.  You can choose stages of different difficulty.
.SH OPTIONS
.TP
.BI "\-\-free\-select"
Allow you to select any stage.  You can select the same stage multiple
times if you use this option.  This is a cheat option.
.TP
.BI "\-\-full\-screen"
Run the game in the full screen mode.
.TP
.BI "\-\-help"
Print a help message and exit.
.TP
.BI "\-\-slow"
Enable the slow mode.  If you use this option,  you can run the game
at the half speed by pressing the s key.  Press the s key again to play
at the normal speed.  This is a cheat option.
.TP
.BI "\-\-version"
Print version information, license information and the disclaimer, then exit.
.SH FILES
.TP
.I "$HOME/.dangen/"
The play record is saved in this directory.
.SH BUGS
Please report any bugs you find to Oohara Yuuma
<oohara@libra.interq.or.jp>.
.SH AUTHOR
Oohara Yuuma <oohara@libra.interq.or.jp>
